#!/bin/bash

# 生产环境部署脚本

# 设置环境变量
export OSS_ACCESS_KEY_ID=${OSS_ACCESS_KEY_ID}
export OSS_ACCESS_KEY_SECRET=${OSS_ACCESS_KEY_SECRET}
export OSS_BUCKET_NAME=${OSS_BUCKET_NAME}
export OSS_ENDPOINT=${OSS_ENDPOINT}

export DB_URL=${DB_URL}
export DB_USERNAME=${DB_USERNAME}
export DB_PASSWORD=${DB_PASSWORD}

export REDIS_HOST=${REDIS_HOST}
export REDIS_PORT=${REDIS_PORT}
export REDIS_PASSWORD=${REDIS_PASSWORD}

export JWT_SECRET=${JWT_SECRET}
export WECHAT_APPID=${WECHAT_APPID}
export WECHAT_SECRET=${WECHAT_SECRET}

export SERVER_PORT=${SERVER_PORT:-48080}

# 启动应用
java -jar ai-paint-backend-1.0-SNAPSHOT.jar
